# Generated by Django 4.1.3 on 2024-04-23 20:43

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ID', models.PositiveIntegerField(default=0)),
                ('property_ID', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('category', models.CharField(choices=[('APARTMENT', 'Apartment'), ('VILLA', 'Villa'), ('HOUSE', 'House'), ('APARTMENT', 'Apartment'), ('OFFICE', 'Office'), ('STUDIO', 'Studio'), ('SHOP', 'Shop')], max_length=10)),
                ('description', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('image1', models.ImageField(upload_to='images/properties/')),
                ('image2', models.ImageField(upload_to='images/properties/')),
                ('image3', models.ImageField(upload_to='images/properties/')),
                ('size', models.PositiveIntegerField(default=1)),
                ('Bathrooms', models.PositiveIntegerField(default=1)),
                ('Bedrooms', models.PositiveIntegerField(default=1)),
                ('seller_ID', models.PositiveIntegerField(default=0, null=True)),
                ('Buy', models.BooleanField(default=False)),
                ('city', models.CharField(default='City', max_length=50)),
                ('floor_number', models.PositiveIntegerField(default=1)),
                ('apartment_number', models.PositiveIntegerField(default=1)),
                ('installment_years', models.PositiveIntegerField(default=1)),
                ('longitude', models.DecimalField(decimal_places=15, default=0, max_digits=19)),
                ('latitude', models.DecimalField(decimal_places=15, default=0, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name=django.contrib.auth.models.User)),
                ('phone', models.PositiveIntegerField(blank=True, default=0)),
                ('street', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
